version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: ember-cli
    versions:
    - 3.23.0
    - 3.24.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
  - dependency-name: ember-source
    versions:
    - 3.24.0
    - 3.24.1
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
  - dependency-name: ember-cli-version-checker
    versions:
    - 5.1.1
  - dependency-name: release-it
    versions:
    - 14.2.2
